parameters:
  BuildProject: "$(Build.SourcesDirectory)/Activities/Community.Activities.sln"
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"
  VmImage: "windows-latest"
  Demands: 
  - msbuild
  - visualstudio
  - vstest
  Dependencies: []
  restoreDependencies: []
  rootPath: $(Build.SourcesDirectory)
  packagesDirectory: $(Build.SourcesDirectory)/packages/
  testList: []
  versionReference: ""

jobs:
- job: CI_Community_Activities_${{ replace(replace(parameters.BuildProject, '/', '_'), '.', '_') }}
  displayName: ${{ replace(replace(parameters.BuildProject, '/', '_'), '.', '_') }}

  pool:
    vmImage: ${{ parameters.VmImage }}
    demands: ${{ parameters.Demands }}

  steps:
  # - powershell: |      
  #     $callUrl = "https://uipath.visualstudio.com/$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)?api-version=4.1"
  #     $callUrl

  #     $authorizationHeaderBytes = [System.Text.ASCIIEncoding]::ASCII.GetBytes(("{0}:{1}" -f "", "$(System.AccessToken)"))
  #     $authorizationHeaderBase64 = [System.Convert]::ToBase64String($authorizationHeaderBytes)
  #     $callHeaders = @{
  #       Accept = "application/json";
  #       Authorization = "Basic $authorizationHeaderBase64";
  #       "Content-Type" = "application/json";
  #     } 

  #     $callBody = @{ keepForever = $true; }

  #     $response = Invoke-RestMethod -Uri $callUrl -Method Patch -Headers $callHeaders -Body ($callBody | ConvertTo-Json -Depth 99)    
  #     if (!$response){ Write-Host "Build retention didn't worked" }
  #   displayName: "Retain build forever"
  #   condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
  #   continueOnError: true

  - task: UniversalPackages@0
    displayName: 'Download BuildRetention tools'
    inputs:
      command: 'download'
      downloadDirectory: '$(Pipeline.Workspace)/toolbox/BuildRetention/'
      feedsToUse: 'internal'
      vstsFeed: 'DevOps'
      vstsFeedPackage: "uipath.devops.tools.buildretention"
      vstsPackageVersion: "1.0.15-dev.1234577"
      verbosity: Error

  - task: PowerShell@2
    displayName: 'update BuildRetention'
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')))
    continueOnError: true 
    inputs:
      targetType: 'filePath'
      filePath: '$(Pipeline.Workspace)/toolbox/BuildRetention/Update-BuildRetentionToForever.ps1'
      arguments: "
      -buildDefinitionName \"$(Build.DefinitionName)\" 
      -projectName \"$(System.TeamProject)\" 
      -authToken \"$(System.AccessToken)\" 
      -buildId \"$(Build.BuildId)\" "
     
      


  - template: "../steps/pre_build.yml"
    parameters:
      rootPath:         ${{ parameters.rootPath }}
      versionReference: ${{ parameters.versionReference }}

  - template: "../steps/build.yml"
    parameters:
      BuildProject:         ${{ parameters.BuildProject }}
      BuildConfiguration:   ${{ parameters.BuildConfiguration }}
      BuildPlatform:        ${{ parameters.BuildPlatform }}
      Dependencies:         ${{ parameters.Dependencies }}
      restoreDependencies:  ${{ parameters.restoreDependencies }}
      rootPath:             ${{ parameters.rootPath }}
      packagesDirectory:    ${{ parameters.packagesDirectory }}

  - template: "../steps/test.yml"
    parameters:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      BuildPlatform:      ${{ parameters.BuildPlatform }}
      rootPath:           ${{ parameters.rootPath }}      
      packagesDirectory:  ${{ parameters.packagesDirectory }}
      testList:           ${{ parameters.testList }}

  - template: "../steps/package.yml"
    parameters:
      BuildProject:       ${{ parameters.BuildProject }}
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      rootPath:           ${{ parameters.rootPath }}
